my_project_directory/src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
     
    private ?string $contenu = null;
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        
        $metadata->addPropertyConstraint('contenu', new Assert\Length([
            'min' => $_ENV["EnvLimitMin"],
            'max' => $_ENV["EnvLimitMax"],
            'minMessage' => 'Votre contenu doit exceder {{ limit }} characters ',
            'maxMessage' => 'Votre contenu ne peut dépasser {{ limit }} characters',
        ]));
    }

    #[ORM\Column(nullable: true)]
    private ?int $id_parent = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getIdParent(): ?int
    {
        return $this->id_parent;
    }

    public function setIdParent(?int $id_parent): self
    {
        $this->id_parent = $id_parent;

        return $this;
    }
    
}

my_project_directory/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }
    public function __toString(){
        return $this->pseudo;
    }
}

my_project_directory/src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Repository\MessageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Message;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\MessageType;

class PostController extends AbstractController
{
    #[Route('/post/{id}', name: 'app_post')]
    public function index(EntityManagerInterface $entityManager ,int $id , MessageRepository $message , MessageRepository $messageRepository , Request $request): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }


        $messages = $message->findBy(['id' => $id]);
        $repository = $messageRepository->findAll();


        $Comm = new Message;
        $FormComm = $this->createForm(MessageType::class, $Comm);
        $FormComm->handleRequest($request);
        if($FormComm->isSubmitted() && $FormComm->isValid())
        {
            
            $Comm->setUser($this->getUser());
            $Comm->setDate(new \DateTime());
            $Comm->setidParent($id);
            //dd($Comm);

            $entityManager->persist($Comm);
            $entityManager->flush();

            return $this->redirectToRoute('app_post', ["id"=>$id] );
        }

        return $this->render('post/index.html.twig', [
            'controller_name' => 'PostController',
            'formComm' => $FormComm->createView(),
            'id' => $messages,
            'user' => $repository,
        ]);
    }
    #[Route('/post/delete/{id}', name: "app_delete2")]
    public function delete2(EntityManagerInterface $entityManager, Message $message): Response
     {  
        $id = $message->getIdParent();
        

         $entityManager->remove($message); 
         $entityManager->flush();
 
         return $this->redirectToRoute('app_post', ["id"=>$id] );
     }
 
     #[Route('/edit/{id}', name: 'app_edit2')]
    public function update2(Request $request , Message $message ,EntityManagerInterface $entityManager): Response
    {
        $edit = $this->createForm(MessageType::class, $message);
        $edit->handleRequest($request);
        if($edit->isSubmitted() && $edit->isValid())
        {
            $entityManager->flush();
            $id = $message->getIdParent();

            return $this->redirectToRoute('app_post', ["id"=>$id] );
        }
        
        return $this->render('edit/index.html.twig', [
            'edit' => $edit->createView(),
            
            
        ]);

    }
}

my_project_directory/templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Post{% endblock %}

{% block body %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<style>
    .flex {display:flex}
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Citation</h1>
    <p>Vous êtes connecté en tant que {{ app.user.userIdentifier }}, <a class="btn btn-sm btn-primary" href="{{ path('app_main') }}">Retour</a></p>
    <p style="font-weight: bold";>Citation de {{id[0].user}} édité le {{id[0].date|date("d/m/y H:i")}}</p>
    <p>{{id[0].contenu}}</p>
   
  
    
    {% for user in user %}
        {% if user.idParent == id[0].id %}
        <p style="font-weight: bold";>Commentaire de {{user.user}}  édité le  {{user.date|date("d/m/y H:i")}}</p>
        <p>{{user.contenu}}</p>
        {% if is_granted("POST_EDIT", user) %}
                <div class="d-flex">
                    <p><a href="/edit/{{user.id}}"  class="btn btn-sm btn-primary px-2">Modification</a></p>
                    <p class="px-2"><a href="/post/delete/{{user.id}}" class="btn btn-sm btn-primary px-2">Suppression</a></p>
                </div>
                {% endif %}
        <hr style="border: 7px solid black";>
        {% endif %}
        
            
        
    {% endfor %}
    
   <div>
    <h2>Ajouter un commentaire</h2>
        
        {{form_start(formComm)}}
        <div class="flex">
        {{form_row(formComm.contenu)}}
        {{form_row(formComm.button)}}
        </div>
        {{form_end(formComm)}}
    </div>
   
    
</div>

{% endblock %}